apiVersion: v1
kind: PersistentVolume
metadata:
  name: deepgtex-prp
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.55.247.179
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deepgtex-prp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
