apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextflow-api
  labels:
    app: nextflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextflow-api
  template:
    metadata:
      labels:
        app: nextflow-api
    spec:
      containers:
      - name: nextflow-api
        image: bentsherman/nextflow-gke
        env:
        - name: NEXTFLOW_K8S
          value: "true"
        command:
        - /bin/bash
        - -c
        - cd /opt/nextflow-api; python3 server.py
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
        volumeMounts:
        - name: vol-1
          mountPath: /workspace
        ports:
        - containerPort: 8080
      volumes:
      - name: vol-1
        persistentVolumeClaim:
          claimName: scidas-cole-test-pvc
