apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-nextflow
  name: nextflow-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-nextflow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-nextflow
    spec:
      containers:
      - name: nextflow-api
        image: cbmckni/scidas-submitter:gke
        command: ["/bin/sh","-c"]
        args: ['printf "%s" "${PROJECTKEY}" > "/home/credential-key.json" && gcloud auth activate-service-account --key-file /home/credential-key.json && gcloud config set project ${PROJECTID} && gcloud container clusters get-credentials ${CLUSTERID} --zone=${ZONE} --project=${PROJECTID} && cd /opt/nextflow-api; python3 server.py']
        env:
        - name: NXF_EXECUTOR
          value: "k8s"
        - name: PROJECTID
          valueFrom:
            configMapKeyRef:
              name: nextflow-api-config
              key: project.id
        - name: PROJECTKEY
          valueFrom:
            configMapKeyRef:
              name: nextflow-api-config
              key: project.key
        - name: CLUSTERID
          valueFrom:
            configMapKeyRef:
              name: nextflow-api-config
              key: project.cluster
        - name: ZONE
          valueFrom:
            configMapKeyRef:
              name: nextflow-api-config
              key: project.zone
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
        volumeMounts:
        - name: vol-1
          mountPath: /workspace
        ports:
        - containerPort: 8080
      volumes:
      - name: vol-1
        persistentVolumeClaim:
          # CHANGE TO CORRECT PVC
          claimName: clemson-pvc

        # RUN "kubectl expose deployment nextflow-api-deployment --type=LoadBalancer --name=nextflow-api-service" after deployment to expose
