apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextflow-api
  labels:
    app: nextflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextflow-api
  template:
    metadata:
      labels:
        app: nextflow-api
    spec:
      containers:
      - name: nextflow-api
        image: bentsherman/nextflow-api
        env:
        - name: NXF_EXECUTOR
          value: "k8s"
        command:
        - /bin/bash
        - -c
        - cd /opt/nextflow-api; scripts/startup.sh
        resources:
          limits:
            cpu: 8
            memory: 4Gi
        volumeMounts:
        - name: vol-1
          mountPath: /workspace
        ports:
        - containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - cd /opt/nextflow-api; scripts/db-backup.sh daily
      volumes:
      - name: vol-1
        persistentVolumeClaim:
          claimName: deepgtex-prp
---
apiVersion: v1
kind: Service
metadata:
  name: nextflow-api
  labels:
    app: nextflow-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: nextflow-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextflow-api
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: nextflow-api.nautilus.optiputer.net
    http:
      paths:
      - path: /
        backend:
          serviceName: nextflow-api
          servicePort: 8080
